version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    container_name: postgres
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db
    ports:
      - "5432:5432"
